# Generated by Django 5.1.3 on 2024-12-11 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total_amount',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='check_in_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='check_out_date',
            new_name='check_out',
        ),
        migrations.RemoveField(
            model_name='additionalservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(blank=True, to='hotel.additionalservice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.reservation'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('matrimonial', 'Matrimonial'), ('presidential', 'Presidential')], max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotel.guest'),
            preserve_default=False,
        ),
    ]
